apiVersion: v1
kind: Service
metadata:
  name: oba-database
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: oba-database
  ports:
  - protocol: TCP
    port: {{ .Values.database.port }}
    targetPort: {{ .Values.database.port }}