apiVersion: apps/v1
kind: Deployment
metadata:
  name: oba-database-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oba-database
  template:
    metadata:
      labels:
        app: oba-database
    spec:
      containers:
        - name: oba-database
          image: {{ .Values.database.image }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oba-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              value: {{ .Values.database.databaseName }}
            - name: MYSQL_USER
              value: {{ .Values.database.user }}
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oba-secrets
                  key: JDBC_PASSWORD
          ports:
            - containerPort: {{ .Values.database.port }}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
      volumes:
        - name: mysql-data
          hostPath:
            path: /var/lib/oba/mysql
