apiVersion: v2
name: one-bus-away
description: A Helm chart for installing OneBusAway
home: https://onebusaway.org
icon: https://developer.onebusaway.org/images/oba-logo.png

type: application

version: 0.1.0

appVersion: "2.5.12"

maintainers:
- name: alanb2718
- name: aaronbrethorst
